### ISSUE TITLE
Code Review 1

### ISSUE THREAD

**Issue by sbmaruf** [yongzx/multilingual-t0#2]
1. MT5 is originally trained on `bfloat16`. we cannot train it on `fp16`. we need to make it `false`, https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/ds_config_zero3.json#L3
2. Can you test if you can improve the batch size to '4' with gradient acc = 16?
3. Make sure you have updated the charts in wandb. Maybe add your wandb API key in the script to log in.
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/train_deepspeed.sh#L32
please note that wandb also visualize gradient, but tensorboard doesn't.
4. We have downloaded the samples from each of the languages by specific ratio. We don't need them at this moment. https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L61
5. You need to write a wrapper for the new dataset that we have downloaded. Download 2-3 languages on your machine and test if that is working properly or not. We are no longer using this way to download datasets. 
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L389-L395 
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L453-L455
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L457
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L459
6. Why don't you add more number of workers for this, https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L559-L565
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L566
7. Let's not add `compute_metrics` for the trainer. If you don't pass it, it will automatically use the loss as `compute_metrics `, 
https://github.com/yongzx/multilingual-t0/blob/91ab683851e30540b0689fb9f7aa38a1c0d1c3d9/multilingual_t0/main.py#L652
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L652 We don't need to compute accuracy here, https://github.com/yongzx/multilingual-t0/blob/91ab683851e30540b0689fb9f7aa38a1c0d1c3d9/multilingual_t0/main.py#L615
It will waste time during evaluation.
8. Let's not remove sentinel token from the language model. You only do this for finetuning, not in the language model training. https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L436
9. Add the checkpoints to hub so that we can get live checkpoint, https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.push_to_hub
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L645
10. We are not using the same batch size as `T5` repository. So `max_steps` should be much higher. We need to know the total number of nodes that the code will run, then calculate the effective batch size (# of nodes * batch * gradient acc) and then calculate total number of steps (100,000*1024/our_batch_size) from there.  
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/train_deepspeed.sh#L7

**Comment by yongzx** [comment]
> 1. MT5 is originally trained on bfloat16. we cannot train it on fp16. we need to make it false, https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/ds_config_zero3.json#L3

Right now my default configuration is False for fp16. I can set it on the json file if that's clearer.

<details>

<summary>Slurm Output</summary>

```
## SLURM PROLOG ###############################################################
##    Job ID : 3816489
##  Job Name : exp-001-mt0_lm_adapt
##  Nodelist : gpu2115
##      CPUs : 2
##  Mem/Node : 102400 MB
## Directory : /gpfs/data/sbach/zyong2/mt0/scripts/exp-001
##   Started : Fri Jan 21 21:51:21 EST 2022
###############################################################################
01/21/2022 21:52:03 - WARNING - __main__ - Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
==== Model parameters ====
 ModelArguments(model_name_or_path='google/mt5-xl', config_name=None, tokenizer_name=None, cache_dir='/users/zyong2/data/zyong2/huggingface/mt5_xl', use_fast_tokenizer=False, model_revision='main', use_auth_token=False)
==== Data parameters ====
 DataTrainingArguments(dataset_name='mc4', dataset_config_name=None, seqio_mixture_name=None, overwrite_cache=False, preprocessing_num_workers=4, max_input_length=1024, max_target_length=1024, val_max_target_length=None, pad_to_max_length=True, max_train_samples=None, max_eval_samples=1000, max_predict_samples=None, num_beams=None, ignore_pad_token_for_loss=True, source_prefix=None, forced_bos_token=None)
==== Training/evaluation parameters ====
 Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
bf16=False,
bf16_full_eval=False,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_steps=10,
evaluation_strategy=IntervalStrategy.STEPS,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=8,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=-1,
log_level=-1,
log_level_replica=-1,
log_on_each_node=True,
logging_dir=/users/zyong2/data/zyong2/mt0/data/processed/001/runs/mt5_xxl_2151_01212022,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=100,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
output_dir=/users/zyong2/data/zyong2/mt0/data/processed/001/mt5_xxl,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=/users/zyong2/data/zyong2/mt0/data/processed/001/mt5_xxl,
save_on_each_node=False,
save_steps=500,
save_strategy=IntervalStrategy.STEPS,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_legacy_prediction_loop=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
```

</details>

**Comment by yongzx** [comment]
> 1 . MT5 is originally trained on bfloat16. we cannot train it on fp16. we need to make it false, https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/ds_config_zero3.json#L3

✅ Fixed.

> 2. Can you test if you can improve the batch size to '4' with gradient acc = 16?

On my local GPU V100 (2 GPUs), even batch size of 2 results in CUDA memory error.

> 3. Make sure you have updated the charts in wandb. Maybe add your wandb API key in the script to log in.
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/train_deepspeed.sh#L32
please note that wandb also visualize gradient, but tensorboard doesn't.

No internet during training so we should only use tensorboard.

> 4. We have downloaded the samples from each of the languages by specific ratio. We don't need them at this moment. https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L61

✅ Fixed and has incorporated the codeline to handle downloaded shards of mC4 data.

> 5. You need to write a wrapper for the new dataset that we have downloaded. Download 2-3 languages on your machine and test if that is working properly or not. We are no longer using this way to download datasets.
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L389-L395
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L453-L455
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L457
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L459

✅ Done downloaded all the necessary data to JZ. 

> 6. Why don't you add more number of workers for this, https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L559-L565
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L566

> 7. Let's not add compute_metrics for the trainer. If you don't pass it, it will automatically use the loss as compute_metrics

✅ Fixed.

> 8. Let's not remove sentinel token from the language model. You only do this for finetuning, not in the language model training. https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L436

~~I don't understand, doesn't [T5Tokenizer has 100 sentinel tokens](https://huggingface.co/transformers/v2.10.0/model_doc/t5.html) (Search "100 sentinel tokens")? If I apply resize here, doesn't that mean that we are including the sentinel tokens?~~ 
✅ Fixed with #3

> 9. Add the checkpoints to hub so that we can get live checkpoint, https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.push_to_hub
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L645

No internet during training. 

> 10. We are not using the same batch size as T5 repository. So max_steps should be much higher. We need to know the total number of nodes that the code will run, then calculate the effective batch size (# of nodes * batch * gradient acc) and then calculate total number of steps (100,000*1024/our_batch_size) from there.
https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/train_deepspeed.sh#L7

🚚

---
> Test with ZeRO v2 instead of v3. 

Using https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/ds_config_zero2.json (with lower `reduce_bucket_size` and `allgather_bucket_size`) I still get CUDA error.

**Comment by sbmaruf** [comment]
> ❓I don't understand, doesn't [T5Tokenizer has 100 sentinel tokens](https://huggingface.co/transformers/v2.10.0/model_doc/t5.html) (Search "100 sentinel tokens")? If I apply resize here, doesn't that mean that we are including the sentinel tokens?

Please check the following google colab. 
https://colab.research.google.com/drive/1JE3a_kRVpN48DZHSZudv333j7PI8bLdn?usp=sharing

**Comment by lintangsutawika** [comment]
> 4. We have downloaded the samples from each of the languages by specific ratio. We don't need them at this moment. https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L61

No, we did not. All languages except English, Russian, Spanish, German, and French are downloaded in full and still requires a probability number to upsample. Yong's implementation should be correct.

> 7. Let's not add compute_metrics for the trainer. If you don't pass it, it will automatically use the loss as compute_metrics ,

No need to worry about this for now. Just don't pass `predict_with_generate = True` which I don't think we won't since we are training for 100k without doing evaluation.

> 8. Let's not remove sentinel token from the language model. You only do this for finetuning, not in the language model training. https://github.com/yongzx/multilingual-t0/blob/lm_adaptation/multilingual_t0/main.py#L436

I agree. Fixed: https://github.com/yongzx/multilingual-t0/pull/3
